script: bash ./deploy.sh
language: php
php:
- 7.0
env:
  global:
  - GH_REF: github.com/UDOOboard/IoT-Docs.git
  - secure: "R/yYlwaJE3sAxPBHaQxuHkD9xdcOvJvkohvXO3Wi/VuJM/oysRcHIXhSvcr+eEPVTylGdSTiOqulzO2p6rWU8WGi+24TkH4zfmHDtkZP1ubX7GeSVdVz39/MOVRHZHH/4vu4wur1ksjmN2+oPbeRVHwAVZY8ZlAjKSFCZ81GJGcKrN3tEdHzrga4SPdhA7TorID0KHokXq8VDbld//4CTJgY4q65heGZePDIDVVc7u8elDbyOFh3f/zIEw7T2W9D/nUNRNhSQQ4tHOAZkEJgidlYyQyaB0HzGUk7Qk0e+2Hv2pdqKj24e4g+WNBAeuPX+6xCCz/qySLGruyMBLF+8QnNla9Kk5APdxPDXlbG5L75Vqc32W5qviqHnXEkuEvhwOfbvewnxOyW4+hhTLJDZGcQHw5aSMr2t8C1ZDNtu1LgAF8Jbzs4OZCpktpu8d52BYEPuvc9qS8d96IznLqqdiFXEWkyiz6chotvs7dRWQ0UocrcN+znxpDiXfm5fZ/hQaFxolepouXwIP6DY3TXW0LXGvDEaJ1vjb+51NbBjCArpXCH0oIFT/u4mqEilIQCOFX4kRMUhC2VP8QbQ1J0JLZqzx+cd+Hj5Vhr6/2Jxw2D8tvqoHim03ERigd4repL1yqNslGodaI16sb5Ql/jd3cLuK7GAX7+HOl5E+x2HCY="
